components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              enum:
                - BAD_REQUEST
                - UNAUTHORIZED
                - NOT_FOUND
                - RATE_LIMITED
                - UPSTREAM_ERROR
                - INTERNAL_ERROR
              example: BAD_REQUEST
            message:
              type: string
              example: "radius too large"
            traceId:
              type: string
              example: "abc123"
          required:
            - code
            - message
            - traceId
      required:
        - error

    SearchResult:
      type: object
      properties:
        placeId:
          type: string
          example: "ChIJ123..."
        name:
          type: string
          example: "Mamma Mia Trattoria"
        rating:
          type: number
          example: 4.6
        userRatingsTotal:
          type: number
          example: 312
        category:
          type: string
          example: "Italian restaurant"
        locality:
          type: string
          example: "Indiranagar, Bengaluru"
        distanceMeters:
          type: number
          example: 540

    SearchResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/SearchResult'
        nextPageToken:
          type: string
          nullable: true

    PlaceDetails:
      type: object
      properties:
        placeId:
          type: string
          example: "ChIJ123..."
        name:
          type: string
          example: "Mamma Mia Trattoria"
        rating:
          type: number
          example: 4.6
        userRatingsTotal:
          type: number
          example: 312
        category:
          type: string
          example: "Italian restaurant"
        locality:
          type: string
          example: "Indiranagar, Bengaluru"
        openingHours:
          type: object
          nullable: true
          properties:
            isOpenNow:
              type: boolean
              example: true
        reviews:
          type: array
          maxItems: 5
          items:
            type: object
            properties:
              rating:
                type: number
                example: 5
              author:
                type: string
                example: "Priya S."
              relativeTime:
                type: string
                example: "2 weeks ago"
              text:
                type: string
                example: "Pesto pasta was outstanding."

    HealthResponse:
      type: object
      properties:
        ok:
          type: boolean
          example: true
        version:
          type: string
          example: "1.0.0"
        uptimeSec:
          type: number
          example: 12345
        timestamp:
          type: string
          format: date-time
          example: "2023-12-01T10:30:00.000Z"
        environment:
          type: string
          example: "development"

tags:
  - name: Search
    description: Business search operations
  - name: Place
    description: Place details and information
  - name: Health
    description: Health checks and monitoring

